# Generated by Django 2.1.3 on 2018-12-06 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('data', models.DateField()),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('data', models.DateTimeField(auto_now=True)),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Person'),
        ),
    ]
